# ===========================
# Drosera Config - Hoodi Testnet
# ===========================

# RPC endpoints
ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc  = "https://ethereum-hoodi-rpc.publicnode.com"

# Your Drosera operator address (use your deployer address)
drosera_address = "0x0000000000000000000000000000000000000000"

[traps]

[traps.stealth_twap_trap]
# Path to the trap artifact compiled by Foundry
path = "out/StealthTWAPTrap.sol/StealthTWAPTrap.json"

# Replace this with deployed address from `DeployTrap.s.sol`
address = "0x0000000000000000000000000000000000000000"

# Optional response contract (you can leave as default if not using one yet)
response_contract = "0x0000000000000000000000000000000000000000"
response_function = "handleTWAPEvent(address,uint256)" 

# Trap settings
cooldown_period_blocks = 10
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 5

private_trap = false
whitelist = []
