ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.stealth_twap_trap]
path = "out/StealthTWAPTrap.sol/StealthTWAPTrap.json"
address = "0x0000000000000000000000000000000000000000"
response_contract = "0x0000000000000000000000000000000000000000"
response_function = "handleTWAPEvent(address,uint256)"
sample_window_blocks = 20
block_sample_size = 5
cooldown_period_blocks = 10
min_number_of_operators = 1
max_number_of_operators = 1
private_trap = true
whitelist = ["0xfb3d951fa8496c6933ea0275695bca906c58527e"]
