[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache = true
evm_version = "paris"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
hoodi = "https://ethereum-hoodi-rpc.publicnode.com"

[etherscan]
hoodi = { key = "<your-etherscan-or-blockscout-api-key-if-available>" }
