[profile.default]
# Project structure
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.20"
optimizer = true
optimizer_runs = 200
evm_version = "shanghai"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

fs_permissions = [
    { access = "read", path = "./out" },
    { access = "read", path = "./lib" }
]

gas_reports = ["*"]
gas_price = "auto"

verbosity = 3

bytecode_hash = "none"
cbor_metadata = false

[rpc_endpoints]
hoodi = "https://ethereum-hoodi-rpc.publicnode.com"
drosera = "https://relay.hoodi.drosera.io"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
quote_style = "double"
int_types = "long"

[fuzz]
runs = 256

[invariant]
runs = 50
depth = 20
fail_on_revert = false
